apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcr-image-pull-secret
spec:
  refreshInterval: 3600s
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: gcr-image-pull-secret
    template:
        type: kubernetes.io/dockerconfigjson
        data:
            .dockerconfigjson: |
                {
                  "auths": {
                    "{{ "{{" }} .registry {{ "}}" }}": {
                      "username": "{{ "{{" }} .username {{ "}}" }}",
                      "password": "{{ "{{" }} .password {{ "}}" }}",
                      "email": "{{ "{{" }} .registryEmail {{ "}}" }}",
                      "auth": "{{ "{{" }} list .username .password | join ":" | b64enc {{ "}}" }}"
                    }
                  }
                }
  data:
    - secretKey: registry
      remoteRef:
        key: initial-secret
        property: GAR_REGISTRY

    - secretKey: username
      remoteRef:
        key: initial-secret
        property: GAR_USERNAME

    - secretKey: password
      remoteRef:
        key: initial-secret
        property: GAR_PASSWORD

    - secretKey: registryEmail
      remoteRef:
        key: initial-secret
        property: GAR_EMAIL
