apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scb-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - {{ .Values.domainScb }}
      secretName: scb-cert
  rules:
    - host: {{ .Values.domainScb }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promrub-{{ .Values.envAlias }}-promrub-scb
                port:
                  number: 80
