apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: konga-credentials
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: konga-credentials       # name of the k8s Secret to be created
  data:
  - secretKey: konga-nodes.cfg
    remoteRef:
      key: initial-secret
      property: KONGA_NODES_CONFIG

  - secretKey: konga-users.cfg
    remoteRef:
      key: initial-secret
      property: KONGA_USERS_CONFIG
