apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true

    services:
    - name: scb-service
      url: http://promrub-{{ .Values.envAlias }}-promrub-scb/
      routes:
      - name: scb
        strip_path: false
        paths:
        - /scb/

    plugins:
    - name: http-log
      service: scb-service
      config:
        http_endpoint: http://logstash-http-to-kafka.analytic-{{ .Values.envAlias }}.svc.cluster.local:8080/
        method: POST
        timeout: 1000
        keepalive: 1000
        flush_timeout: 2
        retry_count: 15
