apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payment-react-ui-ing
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - {{ .Values.domainPaymentReactUI }}
      secretName: payment-react-ui-cert
  rules:
    - host: {{ .Values.domainPaymentReactUI }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: promrub-{{ .Values.envAlias }}-payment-react-ui
                port:
                  number: 80
