apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: scb-appsetting
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s-secret-store      # name of the SecretStore (or kind specified)
  target:
    name: scb-appsetting        # name of the k8s Secret to be created
  data:
  - secretKey: appsettings.json
    remoteRef:
      key: initial-secret
      property: APP_SETTING_SCB
