apiVersion: v2
name: helm-promrub
description: A Helm chart for Promrub

type: application

version: 1.0.0

appVersion: "1.0"

dependencies:
  ### Kong ###
  - name: kong
    version: "2.22.0"
    repository: "https://charts.konghq.com"
    condition: kong.enabled

  - name: "generic-app"
    alias: konga
    condition: konga.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  ### SCB ###
  - name: "generic-app"
    alias: promrub-scb
    condition: promrub-scb.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  ### pgSQL ###
  - name: "postgresql"
    alias: postgresql-scb
    condition: postgresql-scb.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "12.5.7"

  ### PG Web - Use one for all PostgreSQL ###
  - name: "pgweb"
    alias: pgweb
    condition: pgweb.enabled
    repository: "https://charts.ectobit.com"
    version: "0.1.8"

  ### Payment UI (payment-channel) ###
  - name: "generic-app"
    alias: payment-ui
    condition: payment-ui.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"

  ### Promrub API ###
  - name: "generic-app"
    alias: promrub-api
    condition: promrub-api.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.14"
