promrub-scb:
  enabled: true
  nameOverride: promrub-scb

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/promrub-scb
    imagePullSecrets :
      - name: gcr-image-pull # TODO : use External-Secret to create this
    volumes:
      - name: appsetting
        secret:
          secretName: scb-appsetting
          optional: false
    volumeMounts:
      - name: appsetting
        mountPath: /app

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http

postgresql-scb:
  enabled: true
  fullnameOverride: postgresql-scb
  auth:
    database: scb
    existingSecret: scb-postgres-secret
    secretKeys:
      adminPasswordKey: adminPasswordKey
