envAlias: production
domainScb: scb-api.promrub.prom.co.th
domainKonga: konga.promrub.prom.co.th
domainKong: api.promrub.prom.co.th
domainPub: promptrub.com

promrub-scb:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
