kong:
  enabled: true
  fullnameOverride: kong
  proxy:
    type: ClusterIP

  dblessConfig:
    configMap: kong-config

  env:
    database: "off"

  customEnv:
    DUMMY: "006" #Update this when Kong configuration is changed in order to restart the pods

  ingressController:
    enabled: false # This is required in DB less mode

  admin:
    enabled: true
    type: ClusterIP
    http:
      enabled: true

konga:
  nameOverride: konga
  enabled: true
  podDisruptionBudget:
    enabled: false
  pods:
    controller: deployment
    image:
      name: "pantsel/konga"
      tag: "latest"
    ports:
      - name: http
        containerPort: 1337
        protocol: TCP
    env:
      - name: KONGA_SEED_USER_DATA_SOURCE_FILE
        value: /configs/konga-users.cfg

      - name: KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE
        value: /configs/konga-nodes.cfg
    volumes:
      - name: config
        secret:
          secretName: konga-credentials
          optional: false
    volumeMounts:
      - name: config
        mountPath: /configs
  ingress:
    enabled: false

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 1337
        protocol: TCP
        name: http

### Promrub SCB ###
promrub-scb:
  enabled: true
  nameOverride: promrub-scb

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/promrub-scb
    imagePullSecrets :
      - name: gcr-image-pull # TODO : use External-Secret to create this
    volumes:
      - name: appsetting
        secret:
          secretName: scb-appsetting
          optional: false
    volumeMounts:
      - name: appsetting
        mountPath: /app/appsettings.json
        subPath: appsettings.json

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http

postgresql-scb:
  enabled: true
  fullnameOverride: postgresql-scb
  auth:
    database: scb
    existingSecret: scb-postgres-secret
    secretKeys:
      adminPasswordKey: adminPasswordKey

### PG Web ###
pgweb:
  #CREATE USER bank WITH PASSWORD 'xxxxx';
  #GRANT ALL ON ALL TABLES IN SCHEMA public TO bank;
  enabled: true
  nameOverride: pgweb
  ingress:
    enabled: false

payment-ui:
  enabled: true
  nameOverride: payment-ui

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/promrub-payment-ui
    imagePullSecrets :
      - name: gcr-image-pull # TODO : use External-Secret to create this

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http

promrub-api:
  enabled: true
  nameOverride: promrub-api

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/promrub-api
    imagePullSecrets :
      - name: gcr-image-pull # TODO : use External-Secret to create this
    #volumes:
    #  - name: appsetting
    #    secret:
    #      secretName: scb-appsetting
    #      optional: false
    #volumeMounts:
    #  - name: appsetting
    #    mountPath: /app/appsettings.json
    #    subPath: appsettings.json

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 8080
        protocol: TCP
        name: http

payment-react-ui:
  enabled: true
  nameOverride: payment-react-ui

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/promrub-payment-react-ui
    imagePullSecrets :
      - name: gcr-image-pull # TODO : use External-Secret to create this

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http
