promrub-scb:
  enabled: true
  nameOverride: promrub-scb

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/promrub-scb
    imagePullSecrets :
      - name: gcr-image-pull # TODO : use External-Secret to create this

  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http

postgresql-scb:
  enabled: true
  fullnameOverride: postgresql-scb

  auth:
    postgresPassword: admin1234983
    database: scb

    #secretKeys:
    #  adminPasswordKey: key
    #postgresPassword: xxxx

