promrub-scb:
  enabled: true
  nameOverride: promrub-scb

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: asia-southeast1-docker.pkg.dev/promrub-personal-use/promrub/promrub-scb
      pullSecrets:
        - name: gcr-image-pull
