envAlias: production
domain: scb-api.promrub.prom.co.th

promrub-scb:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
