envAlias: development
domainScb: scb-api.promrub-dev.prom.co.th
domainKonga: konga.promrub-dev.prom.co.th
domainKong: api.promrub-dev.prom.co.th
domainPub: dev.promrub.com
domainPgAdmin: pgweb.promptrub-dev.prom.co.th
domainPortalUI: dev-payment-channel.promrub.com

promrub-scb:
  ingress:
    enabled: false

  pods:
    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
